# -*- coding: utf-8 -*-
"""Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twP2OTuwqC_rQbatUIIb8RZnGQLpknb9

# Data Cleaning
"""

import pandas as pd

df = pd.read_csv('HR_Dataset Refresh.csv')
df.head()

production_department = df['Department'] == 'Production       '
df[production_department]

df['Department']

"""# Remove whitespaces using strip function"""

df['Department'] = df['Department'].str.strip()

df['Department']

dep = df['Department']  == 'Production'
df[dep]

"""# Clean and remove unwanted data"""

# Adinolfi, Wilson K
# replace(find, replace, regex=True/False)
# ,.?/{}[]()!@#$%^&*
df['Employee_Name'] = df['Employee_Name'].str.replace(',', '', regex=False)

df

df.info()

"""# Convert object column to date time column"""

# to_datetime(column_name, format='%d.%m.%y'/'mixed'/DayFirst=True/False)
# format='%d.%m.%y' -> didn't worked
df['DateofHire'] = pd.to_datetime(df['DateofHire'], format='mixed')

df.info()

df['DateofTermination'] = pd.to_datetime(df['DateofTermination'], format='mixed')

df['LastPerformanceReview_Date'] = pd.to_datetime(df['LastPerformanceReview_Date'], format='mixed')

df



"""# Feature Engineering"""

'''
Extract new data from original data for further analysis
'''

# Extract first name, middle name and last name for employee name
# split(find, number_of_columns, expand=True/False)
df[['First_Name', 'Middle_Name', 'Last_Name']] = df['Employee_Name'].str.split(' ', n=2, expand=True)

df

df['DateofHire']

# Extract year, month and day from date of hire column
df['Year'] = df['DateofHire'].dt.year
df['Month'] = df['DateofHire'].dt.month
df['Day'] = df['DateofHire'].dt.day

df

df['Month_Name'] = df['DateofHire'].dt.month_name()

df

df['Day_Name'] = df['DateofHire'].dt.day_name()

df

# Find total number of employees hired per year
emp_year = df.groupby('Year')['EmpID'].count().reset_index()
emp_year

# Find total number of employees hired per day
emp_day = df.groupby('Day_Name')['EmpID'].count().reset_index()
emp_day

weekday = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
df['Day_Name'] = pd.Categorical(df['Day_Name'], categories=weekday)

emp_day = df.groupby('Day_Name', observed=False)['EmpID'].count().reset_index()
emp_day

