# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVcpwfzgGF9UJa5hFFm1hj6dGKMRdeec
"""

# NumPy -> Numerical Python
# Package/Module -> base c programming
# Pandas, Matplotlib, Scipy, Scikit-learn -> Numpy

import numpy as np

list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

print(type(list1))
print(type(list2))

# sum = list1 + list2
# print(sum)

one_list = np.array(list1)
print(type(one_list))

two_list = np.array(list2)
print(type(two_list))

'''
    list1 = [1, 2, 3, 4]
    list2 = [5, 6, 7, 8]
'''

sum = one_list + two_list
print(sum)

# 1D Array
# 2D Array

oneD_array = np.array([1, 3, 4, 5])
type(oneD_array)

twoD_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(type(twoD_array))

sum = oneD_array + twoD_array
print(sum)

# Zeros and Ones
'''
Zeros -> To create array of Zero numeric value.
Ones -> To create array of Ones numeric value.

It accepts 2 arguments.
Argument1 -> (row and columns)
Argument2 -> (data type)

binary classification (0 and 1) / Image Classification

cat image -> 0

dog image -> 1
'''

zero_array = np.zeros(5, dtype=int)
print(zero_array)

ones_array = np.ones(5, dtype=int)
print(ones_array)

zero2_array = np.zeros(
        (4, 3), dtype=int
)
zero2_array

one2_array = np.ones(
        (4, 3), dtype=int
)
one2_array

"""# arange"""

for i in range(10):
    print(i)

'''
Arange -> arange(start, stop, step)
'''

data = np.arange(1, 11, 3)
data

"""# Reshape and Ravel"""

'''
Reshape -> Array shape -> (5, 4) -> (4, 5) (2, 10)
Ravel -> (5, 4) -> NDArray -> 1D array
'''

numbers = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20]
])

numbers

numbers.shape

numbers.reshape(2, 10)

numbers.reshape(4, 5)



df = numbers.ravel()

df.shape

"""# UFuncs (Universal Functions)"""

numbers.max()

numbers.min()

numbers.mean()

numbers.sum()



"""# Slicing"""

data = numbers.ravel()

data

# Slicing Syntax
# data[start:stop:step]
data[3:8]

fruits = np.array(["Apple", 'Apple', 'Banana', 'Banana', 'Carrot', 'Dragon Fruit', 'Coconut'])

fruits

fruits[2:4]

data[7:]



'''
2D Array Slicing
-------------------
array[row, column]
'''

df = np.arange(1, 61)
df

data = df.reshape(5, 12)
data

data[1:3, 2:5]

list = [1, 2, 3, 4]

list[10]

"""# Boolean Indexing and Broadcasting

## Boolean Indexing
"""

'''
Used for Data Filtering using condition
-----------------
use case: For data analysis
output: True/False
'''

df = data.ravel()
df

# Find numbers greater than 50
filter = df > 50
filter

df[filter]



fruits

filter_fruit = fruits == 'Apple'
filter_fruit

fruits[filter_fruit]



"""## Broadcasting"""

'''
Rules of Array Broadcasting
-------------------------------
1. All array's shape must be equal
2. [row, column] -> either row or column shape must be 1
'''

oneD_array = np.array(
    [1, 2, 3, 5]
)
oneD_array.shape # (1 row , 4 columns)

twoD_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
twoD_array.shape # (3 row , 4 columns)

sum = oneD_array + twoD_array

sum

