# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhn3uToXvC9DNoduUfOmNsSjl2LfIUsE
"""

#pandas: open source data analysis and manupulation

#1D-series
#2D->Data frame

import pandas as pd

"""Series

"""

temp = [20, 30, 44, 35, 36, 24, 45, 56, 12, 34, 23]
type(temp)

temp = pd.Series(temp)

temp

temp[3:8]

"we can also create alphabeticLA INdex in pandas"

s = pd.Series([1, 2, 3, 4, 5], index = ['A', 'B', 'C', 'D', 'E'])

s['B':'D']

s_operation = s*5
s_operation

sl = [1, 2, 3, 4, 5]
sl

sl*5

"""DataFrame"""

details =[
    ["Alice", 20, "London"],
    ["Bob", 50, "New York"],
    ["charles", 25, "paris"]
]

column_names = ['Name', 'Age', 'City']
index = ['A', 'B', 'c']
df = pd.DataFrame(details, columns=column_names, index=index)

df

df.shape  # no of columns and rows

df['A':'C']

df.size #total no of record in dataframe

df['Name']

df[
    ['Name', 'City']
  ]

df['Name'].dtype

df['Age'].dtype

df.columns

#loc -> locaion
#iloc-> integer location

data = {
    'Name': ['Bean', 'Bob', 'John'],
    'Age': [20, 30, 40],
    'City': ['London', 'New York', 'Paris'],
    'Phone': [123, 456, 789],
    'Job':['IT', 'Sales', 'HR']
}

data = {
    'Name': ['Bean', 'Bob', 'John'],
    'Age': [20, 30, 40],
    'City': ['London', 'New York', 'Paris'],
    'Phone': [123, 456, 789],
    'Job':['IT', 'Sales', 'HR']
}
DataFrame = pd.DataFrame(data)

row = DataFrame.loc[0:1, 'Age':'City']
row

row1 = df.loc[
    ['A', 'c'],
    ['Name', 'City']
]
row1

#iloc-> integer location

i_loc = DataFrame.iloc[0:2, 1:4]
i_loc

i_loc = DataFrame.iloc[
    [0, 2], #row
    [1, 3]  #column
]
i_loc

df.loc['A':'B', 'Age':'City']

"""Read DAtaset"""

menu = pd.read_csv('menu.csv')
menu

employes = pd.read_csv('employes.csv')
employes

import pandas as pd

# Create a sample DataFrame for menu items
menu_data = {
    'Item_ID': [101, 102, 103, 104, 105],
    'Name': ['Burger', 'Pizza', 'Salad', 'Fries', 'Drink'],
    'Category': ['Main', 'Main', 'Side', 'Side', 'Beverage'],
    'Price': [12.50, 15.00, 8.75, 4.25, 3.00]
}
menu_df = pd.DataFrame(menu_data)

# Display the DataFrame
display(menu_df)

# Save the DataFrame to a CSV file
menu_df.to_csv('menu.csv', index=False)
print("menu.csv created successfully!")

# Verify the file was created by loading it back
verify_menu_df = pd.read_csv('menu.csv')
print("Content of menu.csv:")
display(verify_menu_df.head())

import pandas as pd

# Create a sample DataFrame for employees
employes_data = {
    'Employee_ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'Engineering', 'Sales', 'Marketing', 'HR'],
    'Salary': [60000, 90000, 75000, 80000, 62000]
}
employes_df = pd.DataFrame(employes_data)

# Display the DataFrame
display(employes_df)

# Save the DataFrame to a CSV file
employes_df.to_csv('employes.csv', index=False)
print("employes.csv created successfully!")

# Verify the file was created by loading it back
verify_df = pd.read_csv('employes.csv')
print("Content of employes.csv:")
display(verify_df.head())

employes_df.head()

employes_df.tail()

employes_df['Name'].dtype

employes_df.info()



employes_df.describe()

df = pd.read_csv('menu.csv')
df

"""Conditional filtering"""

employes_df.info()

# find the details of employes whose salary is gerater than 7000

filter_salary = employes_df['Salary'] > 7000
employes_df[filter_salary]

# find the details of employes whpose salary more than 5000 and less than 15000

salary_details = (employes_df['Salary'] > 5000) & (employes_df['Salary'] < 15000)
employes_df[salary_details]

# or condition

employes['Department'].unique()

# find the details of employes who works in either Ad_PRES or IT_PROG

job_details = employes_df['Department'].isin(['HR', 'Engineering'])
employes_df[job_details]

"""Between and IN"""

salary_details = employes_df['Salary'].between(5000, 15000)
employes_df[salary_details]

